### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by phuicy** [virgileTN/pyopenvr_wrapper_ros#3]
Hey,

To get this working in docker, what devices do I need to pass through?
e.g.
 ```yml
    devices:
     - "/dev/bus/usb:/dev/bus/usb"
     - "/dev/dri:/dev/dri"
     - "/dev/input:/dev/input"
    environment:
     - DISPLAY=unix:0
     - ROS_MASTER_URI=http://192.168.1.161:11311
     - ROS_HOSTNAME=192.168.1.100
    volumes:
     - "/tmp/.X11-unix:/tmp/.X11-unix"  
```

thanks,
Guy
